
services:

  app:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    env_file:
      - .env
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - .docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
